/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastrarRouteImport } from './routes/cadastrar'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as ConviteInviteCodeRouteImport } from './routes/convite/$inviteCode'
import { Route as JogadorEfootballIdRouteImport } from './routes/jogador/$efootballId'
import { Route as LigasIndexRouteImport } from './routes/ligas/index'
import { Route as LigasNovaRouteImport } from './routes/ligas/nova'
import { Route as PerfilIndexRouteImport } from './routes/perfil/index'
import { Route as PerfilReivindicarIdRouteImport } from './routes/perfil/reivindicar-id'
import { Route as LigasLeagueIdIndexRouteImport } from './routes/ligas/$leagueId/index'
import { Route as LigasLeagueIdConvidarRouteImport } from './routes/ligas/$leagueId/convidar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrarRoute = CadastrarRouteImport.update({
  id: '/cadastrar',
  path: '/cadastrar',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteInviteCodeRoute = ConviteInviteCodeRouteImport.update({
  id: '/convite/$inviteCode',
  path: '/convite/$inviteCode',
  getParentRoute: () => rootRouteImport,
} as any)
const JogadorEfootballIdRoute = JogadorEfootballIdRouteImport.update({
  id: '/jogador/$efootballId',
  path: '/jogador/$efootballId',
  getParentRoute: () => rootRouteImport,
} as any)
const LigasIndexRoute = LigasIndexRouteImport.update({
  id: '/ligas/',
  path: '/ligas/',
  getParentRoute: () => rootRouteImport,
} as any)
const LigasNovaRoute = LigasNovaRouteImport.update({
  id: '/ligas/nova',
  path: '/ligas/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilIndexRoute = PerfilIndexRouteImport.update({
  id: '/perfil/',
  path: '/perfil/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilReivindicarIdRoute = PerfilReivindicarIdRouteImport.update({
  id: '/perfil/reivindicar-id',
  path: '/perfil/reivindicar-id',
  getParentRoute: () => rootRouteImport,
} as any)
const LigasLeagueIdIndexRoute = LigasLeagueIdIndexRouteImport.update({
  id: '/ligas/$leagueId/',
  path: '/ligas/$leagueId/',
  getParentRoute: () => rootRouteImport,
} as any)
const LigasLeagueIdConvidarRoute = LigasLeagueIdConvidarRouteImport.update({
  id: '/ligas/$leagueId/convidar',
  path: '/ligas/$leagueId/convidar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastrar': typeof CadastrarRoute
  '/entrar': typeof EntrarRoute
  '/convite/$inviteCode': typeof ConviteInviteCodeRoute
  '/jogador/$efootballId': typeof JogadorEfootballIdRoute
  '/ligas/nova': typeof LigasNovaRoute
  '/perfil/reivindicar-id': typeof PerfilReivindicarIdRoute
  '/ligas/': typeof LigasIndexRoute
  '/perfil/': typeof PerfilIndexRoute
  '/ligas/$leagueId/convidar': typeof LigasLeagueIdConvidarRoute
  '/ligas/$leagueId/': typeof LigasLeagueIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastrar': typeof CadastrarRoute
  '/entrar': typeof EntrarRoute
  '/convite/$inviteCode': typeof ConviteInviteCodeRoute
  '/jogador/$efootballId': typeof JogadorEfootballIdRoute
  '/ligas/nova': typeof LigasNovaRoute
  '/perfil/reivindicar-id': typeof PerfilReivindicarIdRoute
  '/ligas': typeof LigasIndexRoute
  '/perfil': typeof PerfilIndexRoute
  '/ligas/$leagueId/convidar': typeof LigasLeagueIdConvidarRoute
  '/ligas/$leagueId': typeof LigasLeagueIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastrar': typeof CadastrarRoute
  '/entrar': typeof EntrarRoute
  '/convite/$inviteCode': typeof ConviteInviteCodeRoute
  '/jogador/$efootballId': typeof JogadorEfootballIdRoute
  '/ligas/nova': typeof LigasNovaRoute
  '/perfil/reivindicar-id': typeof PerfilReivindicarIdRoute
  '/ligas/': typeof LigasIndexRoute
  '/perfil/': typeof PerfilIndexRoute
  '/ligas/$leagueId/convidar': typeof LigasLeagueIdConvidarRoute
  '/ligas/$leagueId/': typeof LigasLeagueIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastrar'
    | '/entrar'
    | '/convite/$inviteCode'
    | '/jogador/$efootballId'
    | '/ligas/nova'
    | '/perfil/reivindicar-id'
    | '/ligas/'
    | '/perfil/'
    | '/ligas/$leagueId/convidar'
    | '/ligas/$leagueId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastrar'
    | '/entrar'
    | '/convite/$inviteCode'
    | '/jogador/$efootballId'
    | '/ligas/nova'
    | '/perfil/reivindicar-id'
    | '/ligas'
    | '/perfil'
    | '/ligas/$leagueId/convidar'
    | '/ligas/$leagueId'
  id:
    | '__root__'
    | '/'
    | '/cadastrar'
    | '/entrar'
    | '/convite/$inviteCode'
    | '/jogador/$efootballId'
    | '/ligas/nova'
    | '/perfil/reivindicar-id'
    | '/ligas/'
    | '/perfil/'
    | '/ligas/$leagueId/convidar'
    | '/ligas/$leagueId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastrarRoute: typeof CadastrarRoute
  EntrarRoute: typeof EntrarRoute
  ConviteInviteCodeRoute: typeof ConviteInviteCodeRoute
  JogadorEfootballIdRoute: typeof JogadorEfootballIdRoute
  LigasNovaRoute: typeof LigasNovaRoute
  PerfilReivindicarIdRoute: typeof PerfilReivindicarIdRoute
  LigasIndexRoute: typeof LigasIndexRoute
  PerfilIndexRoute: typeof PerfilIndexRoute
  LigasLeagueIdConvidarRoute: typeof LigasLeagueIdConvidarRoute
  LigasLeagueIdIndexRoute: typeof LigasLeagueIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastrar': {
      id: '/cadastrar'
      path: '/cadastrar'
      fullPath: '/cadastrar'
      preLoaderRoute: typeof CadastrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/$inviteCode': {
      id: '/convite/$inviteCode'
      path: '/convite/$inviteCode'
      fullPath: '/convite/$inviteCode'
      preLoaderRoute: typeof ConviteInviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogador/$efootballId': {
      id: '/jogador/$efootballId'
      path: '/jogador/$efootballId'
      fullPath: '/jogador/$efootballId'
      preLoaderRoute: typeof JogadorEfootballIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ligas/': {
      id: '/ligas/'
      path: '/ligas'
      fullPath: '/ligas/'
      preLoaderRoute: typeof LigasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ligas/nova': {
      id: '/ligas/nova'
      path: '/ligas/nova'
      fullPath: '/ligas/nova'
      preLoaderRoute: typeof LigasNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/': {
      id: '/perfil/'
      path: '/perfil'
      fullPath: '/perfil/'
      preLoaderRoute: typeof PerfilIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/reivindicar-id': {
      id: '/perfil/reivindicar-id'
      path: '/perfil/reivindicar-id'
      fullPath: '/perfil/reivindicar-id'
      preLoaderRoute: typeof PerfilReivindicarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ligas/$leagueId/': {
      id: '/ligas/$leagueId/'
      path: '/ligas/$leagueId'
      fullPath: '/ligas/$leagueId/'
      preLoaderRoute: typeof LigasLeagueIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ligas/$leagueId/convidar': {
      id: '/ligas/$leagueId/convidar'
      path: '/ligas/$leagueId/convidar'
      fullPath: '/ligas/$leagueId/convidar'
      preLoaderRoute: typeof LigasLeagueIdConvidarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastrarRoute: CadastrarRoute,
  EntrarRoute: EntrarRoute,
  ConviteInviteCodeRoute: ConviteInviteCodeRoute,
  JogadorEfootballIdRoute: JogadorEfootballIdRoute,
  LigasNovaRoute: LigasNovaRoute,
  PerfilReivindicarIdRoute: PerfilReivindicarIdRoute,
  LigasIndexRoute: LigasIndexRoute,
  PerfilIndexRoute: PerfilIndexRoute,
  LigasLeagueIdConvidarRoute: LigasLeagueIdConvidarRoute,
  LigasLeagueIdIndexRoute: LigasLeagueIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
